export const PLAYER_CONNECTED = 'PLAYER_CONNECTED';
export const PLAYER_DISCONNECTED = 'PLAYER_DISCONNECTED';
export const START_GAME = 'START_GAME';
export const NOT_ENOUGH_PLAYERS = 'NOT_ENOUGH_PLAYERS';
export const TOO_MANY_PLAYERS = 'TOO_MANY_PLAYERS';